### PR TITLE
Update Ice to 3.6.3

### PR DESCRIPTION
**Pull request by Kissaki**
I think the nuget patch did not apply, so I removed it. I will try again whether this is the case.

### CODE REVIEW

**Comment by Kissaki** [comment]
Confirmed. It fails to apply, that is why I removed it.
Searching for "nuget" in either of the patched files does not yield any results. I guess the nuget logic was removed(?).

**Comment by mkrautz** [comment]
Fails to build for me:

	        link.exe user32.lib gdi32.lib dbghelp.lib wsock32.lib ws2_32.lib iphlpapi.lib rpcrt4.lib advapi32.lib crypt32.lib secur32.lib mcpp.lib libbz2.lib libexpat.lib libdb53.lib /LIBPATH:C:\MumbleBuild\win64-static-no-ltcg-1.3.x-2017-03-26-d219ea1-825\mcpp /LIBPATH:C:\MumbleBuild\win64-static-no-ltcg-1.3.x-2017-03-26-d219ea1-825\bzip2\lib /LIBPATH:C:\MumbleBuild\win64-static-no-ltcg-1.3.x-2017-03-26-d219ea1-825\expat\lib /LIBPATH:C:\MumbleBuild\win64-static-no-ltcg-1.3.x-2017-03-26-d219ea1-825\berkeleydb\lib /nologo /OPT:REF /debug /incremental:no /LIBPATH:"..\lib"   /nologo /OPT:REF /debug /incremental:no /LIBPATH:"..\..\lib"   /pdb:..\..\bin\slice2cpp.pdb .\Gen.obj  .\Main.obj setargv.obj /out:..\..\bin\slice2cpp.exe    Slice2Cpp.res
	   Creating library ..\..\bin\slice2cpp.lib and object ..\..\bin\slice2cpp.exp
	IceUtil.lib(FileUtil.obj) : error LNK2019: unresolved external symbol __imp_PathIsDirectoryEmptyW referenced in function "bool __cdecl IceUtilInternal::isEmptyDirectory(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?isEmptyDirectory@IceUtilInternal@@YA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
	..\..\bin\slice2cpp.exe : fatal error LNK1120: 1 unresolved externals
	NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe"' : return code '0x460'
	Stop.
	NMAKE : fatal error U1077: 'for' : return code '0x1'
	Stop.
	NMAKE : fatal error U1077: 'for' : return code '0x1'
	Stop.
	+ exit 2

**Comment by mkrautz** [comment]
Added shlwapi.lib to ICE_LDFLAGS, gets further...

**Comment by mkrautz** [comment]
The nuget stuff is still there, in mostly the same place as it were in 3.6.3. I've created an updated patch (not yet committed here... still building...)

**Pull request merged**
