### PR TITLE
buildenv/1.3.x/win32-static: add support for MSVC 2017

### PR DESCRIPTION
**Pull request by davidebeatrici**

### CODE REVIEW

**Comment by mkrautz** [comment]
LGTM.

**Comment by mkrautz** [comment]
Why is it WIP? @davidebeatrici? Please remedy and submit if OK.

**Comment by davidebeatrici** [comment]
> Why is it WIP? @davidebeatrici? Please remedy and submit if OK.

It requires #80.

**Comment by mkrautz** [comment]
@davidebeatrici Let's land it and keep the default VSVER to 14.0? Then after landing the dep update, we can bump this?

**Pull request merged**
