### PR TITLE
buildenv/1.3.x: merge Windows directories in a single one

### PR DESCRIPTION
**Pull request by davidebeatrici**
There's no need for multiple different directories, as the only thing that changes between a build type and another are the parameters passed to `setup.cmd`.

### CODE REVIEW

**Comment by mkrautz** [comment]
I obviously prefer the directory approach, such that each target has its own directory, and the uniform way to create a buildenv is to just run setup.cmd.

**Comment by davidebeatrici** [comment]
The problem is that if we change a dependency build script for a single target, we have to do it in the `win32-static` directory anyway.

**Comment by mkrautz** [comment]
I did it this way, mostly to have clear documentation.

However, I can see wanting this, but I don't really see it as a big priority?... I don't see what's too wrong with the old approach?

**Comment by davidebeatrici** [comment]
#80 is currently not suitable to build Mumble for Windows XP, because Qt doesn't support it anymore.

As we discussed, I would like to keep Qt 5.6 for x86 and update to Qt 5.9 for x64, meaning that `win32-static` and `win64-static` have to use different build scripts.

We could keep the directories separated and provide the two build scripts in `win32-static`, but I think that it would cause confusion.

**Pull request merged**
