### PR TITLE
Turning off bearer management for qt5 os x build as it causes strange la...

### PR DESCRIPTION
**Pull request by NitroPye**
...tency issues on wifi

### CODE REVIEW

**Comment by mkrautz** [comment]
Trying out a build at the moment...

**Comment by mkrautz** [comment]
Thanks! Landed as 36d2daac2ef856c4556c95b08ed8715dfb1cf260.

I will rebuild the build env for OS X, and when that's done, build a new snapshot.

**Comment by mraakashshah** [comment]
A very similar problem is occurring for me when I play Heroes of the Storm, also. However, I am on a Windows 8.1 machine. Would this fix for OSX have also negated any problems in Windows?

**Comment by mkrautz** [comment]
I think we still have bearer stuff enabled on Windows. Should probably just disable it there as well.

**Pull request closed without merging**
